### ISSUE TITLE
iowait spike bug with mpstat 10.0.3

### ISSUE THREAD

**Issue by celenechang** [sysstat/sysstat#14]
Several of our and our clients' hosts are experiencing large spikes in iowait measures using mpstat.

The range of the spike varies, we have seen values between 80K and 12M. These spikes occur occasionally on specific hosts, for instance 1-2x/week. The rest of the time the values reported are within normal range.

All hosts (~10 that we checked) that are reporting this phenomenon have mpstat version 10.0.3. 

Hosts that haven't shown any spikes in the past month (6 checked) are on 9.0.6.

Thanks!

**Comment by brendasilver** [comment]
like reading a good novel .. then suddenly the dog runs away with the book ... What happened? Was this mystery ever solved ?

**Comment by l1x** [comment]
Not that I am aware of. It seems like an integer overflow or something similar. We fixed it on our side by discarding anything that is % and bigger than 100 as the workaround.

**Comment by xplode** [comment]
We have also seen this problem regularly occur on our production virtual instances.  We started monitoring it a couple months back and get a bad iowait value from sar a few times a week.  The sar output looks like:
`04:04:55        all      0.80      0.00      0.20    107562416.60      0.00     99.02`

We are also ignoring values above 100.

**Comment by bugfood** [comment]
I investigated this issue (or one like it). We have a nearly-idle physical host that gets these anomalous values now and then. I examined the problem some, and as far as I can tell, the problem is that the iowait counters in /proc/stat sometimes jump backwards by a small amount (-1 to -22) for one or more individual CPUs. Since the host has very little actual iowait, these small negative values can sometimes be enough to make the overall sum across CPUs be negative. This triggers code in mpstat for detecting 32-bit counter overflow, resulting in a large wrong value.

Here is a log of this activity:
[proc-stat.log.gz](https://github.com/sysstat/sysstat/files/3110068/proc-stat.log.gz)
...and the analysis script:
[stat2.pl.gz](https://github.com/sysstat/sysstat/files/3110069/stat2.pl.gz)

I can't think of any valid reason for the counters to go backward (other than overflow, which is clearly not happening). I suspect a kernel bug. This is on an old redhat kernel:

2.6.32-431.23.3.el6.x86_64

...and sysstat 9.0.4.


After that, I compiled sysstat 12.0.3. I have not (yet) observed the problem with that version, probably because of these commits:
https://github.com/sysstat/sysstat/commit/535bc3577a233d4ce334ab557df29760e22889e9
https://github.com/sysstat/sysstat/commit/9057b41fcbf509a6dd2cefe8be31c7181e3c905c

I do note that those code changes appear to work around the problem by accident, and there is still an underlying problem in the kernel's reporting to /proc/stat (at least that old kernel).

-Corey

**Comment by l1x** [comment]
We forgot the celebrate the 5th birthday of this bug. We can prep for the 10th birthday though. :)

**Comment by SuperQ** [comment]
FYI, I see the same iostat jump-backs on more modern kernels. For example, here is a more up-to-date 4.15.0 kernel:

The iowait for one CPU jumped forward by 10ms and then back to the previous value. (Note, these values are in seconds, translated from /proc/stat)

value @ timestamp
3161.91 @ 1582699800.459
3161.91 @ 1582699815.459
3161.91 @ 1582699830.459
3161.91 @ 1582699845.459
**3161.92** @ 1582699860.459
3161.91 @ 1582699875.459
3161.91 @ 1582699890.459
3161.91 @ 1582699905.459
3161.91 @ 1582699920.459
3161.91 @ 1582699935.459
3161.91 @ 1582699950.459
3161.91 @ 1582699965.459
3161.92 @ 1582699980.459
3161.92 @ 1582699995.459
3161.92 @ 1582700010.459
3161.92 @ 1582700025.459

So this is very much a persistent kernel bug in tacking iowait.

**Comment by l1x** [comment]
Let's schedule the 10th birthday. We could go to Vegas and close this ticket there and never talk about it ever again.

**Comment by petrpavlu** [comment]
The following is a bit of history digging into this problem, for sar in particular.

Test procedure:
* Run `sadc 1 4 test.sa` to collect sample data.
* Open `test.sa` in an editor and set the iowait value for the CPUs "all" and #0 in the third sample to be same as in the second sample minus 1, thus making the value to decrement. Save the modified file as `test-modified.sa`.
* Run `sar -f test-modified.sa -P ALL` to observe reported information.

Commits that are of interest:
* https://github.com/sysstat/sysstat/commit/1655f22d0c6d1f23fe3d167936ae54eb2a50cff1 -- workaround for /proc/stat go backward,
* https://github.com/sysstat/sysstat/commit/535bc3577a233d4ce334ab557df29760e22889e9 -- Workaround for offline CPU coming back online,
* https://github.com/sysstat/sysstat/commit/ef3301e2ab3e54124b2dc2171f0cf1217f79fa43 -- sar: Compute global CPU stats as the sum of individual ones.

1. Prior to 1655f22d0c6d1f23fe3d167936ae54eb2a50cff1:

       1-1655f22> sar -f test-modified.sa -P ALL
       Linux 4.12.14-lp151.28.59-default (linux-h0fc)  08/18/2020      _x86_64_        (1 CPU)
       
       11:03:15 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
       11:03:16 AM     all      0.00      0.00      0.00      0.00      0.00    100.00
       11:03:16 AM       0      0.00      0.00      0.00      0.00      0.00    100.00
       
       11:03:16 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
       11:03:17 AM     all      0.00      0.00      1.00    18446744073709551616.00      0.00     99.00
       11:03:17 AM       0      0.00      0.00      1.01    18633074821928841216.00      0.00    100.00
       
       11:03:17 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
       11:03:18 AM     all      0.00      0.00      0.99      0.99      0.00     99.01
       11:03:18 AM       0      0.00      0.00      0.98      0.98      0.00     98.04
       
       Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
       Average:        all      0.00      0.00      0.66      0.00      0.00     99.34
       Average:          0      0.00      0.00      0.66      0.00      0.00     99.34

   Since 1655f22d0c6d1f23fe3d167936ae54eb2a50cff1:

       1-1655f22> sar -f test-modified.sa -P ALL
       Linux 4.12.14-lp151.28.59-default (linux-h0fc)  08/18/2020      _x86_64_        (1 CPU)
       
       11:03:15 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
       11:03:16 AM     all      0.00      0.00      0.00      0.00      0.00    100.00
       11:03:16 AM       0      0.00      0.00      0.00      0.00      0.00    100.00
       
       11:03:16 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
       11:03:17 AM     all      0.00      0.00      1.00      0.00      0.00     99.00
       11:03:17 AM       0      0.00      0.00      1.01      0.00      0.00    100.00
       
       11:03:17 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
       11:03:18 AM     all      0.00      0.00      0.99      0.99      0.00     99.01
       11:03:18 AM       0      0.00      0.00      0.98      0.98      0.00     98.04
       
       Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
       Average:        all      0.00      0.00      0.66      0.00      0.00     99.34
       Average:          0      0.00      0.00      0.66      0.00      0.00     99.34

   This mostly fixed the problem although a sum of values for CPU #0 at 11:03:17 AM gives 101.01% instead of 100%.

2. Prior to 535bc3577a233d4ce334ab557df29760e22889e9:

       2-535bc35> sar -f test-modified.sa -P ALL
       Linux 4.12.14-lp151.28.59-default (linux-h0fc)  08/18/20        _x86_64_        (1 CPU)
       
       12:25:42        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:25:43        all      0.00      0.00      0.00      0.00      0.00    100.00
       12:25:43          0      0.00      0.00      0.00      0.00      0.00    100.00
       
       12:25:43        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:25:44        all      0.00      0.00      0.00      0.00      0.00    101.01
       12:25:44          0      0.00      0.00      0.00      0.00      0.00    101.01
       
       12:25:44        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:25:45        all      0.00      0.00      0.00      0.99      0.00     99.01
       12:25:45          0      0.00      0.00      0.00      0.99      0.00     99.01
       
       Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
       Average:        all      0.00      0.00      0.00      0.00      0.00    100.00
       Average:          0      0.00      0.00      0.00      0.00      0.00    100.00

   Since 535bc3577a233d4ce334ab557df29760e22889e9:

       2-535bc35> sar -f test-modified.sa -P ALL
       Linux 4.12.14-lp151.28.59-default (linux-h0fc)  08/18/20        _x86_64_        (1 CPU)
       
       12:25:42        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:25:43        all      0.00      0.00      0.00      0.00      0.00    100.00
       12:25:43          0      0.00      0.00      0.00      0.00      0.00    100.00
       
       12:25:43        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:25:44        all      0.00      0.00      0.00      0.00      0.00    101.01
       12:25:44          0      0.00      0.00      0.00     98.94      0.00      1.06
       
       12:25:44        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:25:45        all      0.00      0.00      0.00      0.99      0.00     99.01
       12:25:45          0      0.00      0.00      0.00      0.99      0.00     99.01
       
       Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
       Average:        all      0.00      0.00      0.00      0.00      0.00    100.00
       Average:          0      0.00      0.00      0.00      0.00      0.00    100.00

   The problem was reintroduced in a slightly different shape for per-CPU results.

3. Prior to ef3301e2ab3e54124b2dc2171f0cf1217f79fa43:

       3-ef3301e> sar -f test-modified.sa -P ALL
       Linux 4.12.14-lp151.28.59-default (linux-h0fc)  08/18/20        _x86_64_        (1 CPU)
       
       12:48:29        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:48:30        all      0.00      0.00      0.00      0.00      0.00    100.00
       12:48:30          0      0.00      0.00      0.00      0.00      0.00    100.00
       
       12:48:30        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:48:31        all      0.00      0.00      0.00      0.00      0.00    101.01
       12:48:31          0      0.00      0.00      0.00     98.94      0.00      1.06
       
       12:48:31        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:48:32        all      0.00      0.00      0.00      0.99      0.00     99.01
       12:48:32          0      0.00      0.00      0.00      0.99      0.00     99.01
       
       Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
       Average:        all      0.00      0.00      0.00      0.00      0.00    100.00
       Average:          0      0.00      0.00      0.00      0.00      0.00    100.00

   Since ef3301e2ab3e54124b2dc2171f0cf1217f79fa43:

       3-ef3301e> sar -f test-modified.sa -P ALL
       Linux 4.12.14-lp151.28.59-default (linux-h0fc)  08/18/20        _x86_64_        (1 CPU)
       
       12:48:29        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:48:30        all      0.00      0.00      0.00      0.00      0.00    100.00
       12:48:30          0      0.00      0.00      0.00      0.00      0.00    100.00
       
       12:48:30        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:48:31        all      0.00      0.00      0.00     98.94      0.00      1.06
       12:48:31          0      0.00      0.00      0.00     98.94      0.00      1.06
       
       12:48:31        CPU     %user     %nice   %system   %iowait    %steal     %idle
       12:48:32        all      0.00      0.00      0.00      0.99      0.00     99.01
       12:48:32          0      0.00      0.00      0.00      0.99      0.00     99.01
       
       Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
       Average:        all      0.00      0.00      0.00      0.00      0.00    100.00
       Average:          0      0.00      0.00      0.00      0.00      0.00    100.00

   The problem was reintroduced also for the CPU "all" results. Current HEAD (8a797054173954b57cfa23d9e6885adad5ab73d2) behaves in the same way.

All test files are attached as [sysstat-14.tar.gz](https://github.com/sysstat/sysstat/files/5161994/sysstat-14.tar.gz).

On the kernel side, it looks [the most recent attempt](https://lkml.org/lkml/2014/6/26/98) to fix the problem with iowait being decremented was in 2014 but there does not appear to be any progress since then. [Kernel documentation](https://www.kernel.org/doc/Documentation/filesystems/proc.txt) for `/proc/stat` also confirms this behaviour: "The value of iowait field in /proc/stat will decrease in certain conditions."

**Comment by SuperQ** [comment]
FYI I ended up using a metrics value tracking cache in the node_exporter to handle these resets. I've seen reports of other counters jumping backwards since introducing this.

See https://github.com/prometheus/node_exporter/pull/1711 for more details.
