### ISSUE TITLE
Average 0 ?

### ISSUE THREAD

**Issue by rahulruikar** [sysstat/sysstat#157]
Hi,

I often get Average value as 0 even if there other values collected during specified interval
Could you please explain why this average is 0 ?

09:22:57 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
09:23:27 AM     all     17.87      0.00      1.79      0.44      0.00     79.90
09:23:57 AM     all     18.94      0.00      1.64      0.47      0.00     78.96
09:24:27 AM     all     21.46      0.00      0.92      0.15      0.00     77.47
09:24:57 AM     all     21.46      0.00      0.53      0.13      0.00     77.87
09:25:27 AM     all      0.00      0.00      0.00      0.00      0.00      0.00
09:25:57 AM     all     21.44      0.00      0.47      0.08      0.00     78.01
09:26:27 AM     all     21.44      0.00      0.44      0.07      0.00     78.05
09:26:57 AM     all     21.49      0.00      0.57      0.09      0.00     77.86
09:27:27 AM     all      0.00      0.00      0.00      0.00      0.00      0.00
09:27:57 AM     all     21.55      0.00      0.52      0.07      0.00     77.85
Average:        all      0.00      0.00      0.00      0.00      0.00      0.00

**Comment by sysstat** [comment]
Hi,
Please give me more information so that I can help you: sysstat version number, machine architecture, how to reproduce the problem...
Also attach a sar binary data file showing the problem.
Thanks.

**Comment by Samodepalace** [comment]
This particular issue seems readily reproducible using SLES v12 SP3
SLE-12-SP3-Server-DVD-x86_64-GM-DVD1

Both on a Linux VM and using a physical server (HP Proliant BL460c G7)
Per Core average values are missing in the following output from cores 12,13,14 and 15.
The same behaviour is observed in the output from sar -P ALL 2 10 

Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
Average:        all      0.01      0.00      0.01      2.01      0.00     97.98
Average:          0      0.02      0.00      0.00      0.00      0.00     99.98
Average:          1      0.02      0.00      0.00      0.00      0.00     99.98
Average:          2      0.00      0.00      0.00      0.00      0.00    100.00
Average:          3      0.00      0.00      0.00      0.00      0.00    100.00
Average:          4      0.00      0.00      0.00      0.05      0.00     99.95
Average:          5      0.00      0.00      0.00      0.00      0.00    100.00
Average:          6      0.00      0.00      0.00      0.00      0.00    100.00
Average:          7      0.00      0.00      0.00      0.00      0.00    100.00
Average:          8      0.00      0.00      0.00      0.00      0.00    100.00
Average:          9      0.00      0.00      0.00      0.00      0.00    100.00
Average:         10      0.00      0.00      0.00     48.25      0.00     51.75
Average:         11      0.03      0.00      0.00      0.00      0.00     99.97
Average:         12      0.00      0.00      0.00      0.00      0.00      0.00
Average:         13      0.00      0.00      0.00      0.00      0.00      0.00
Average:         14      0.00      0.00      0.00      0.00      0.00      0.00
Average:         15      0.00      0.00      0.00      0.00      0.00      0.00
Average:         16      0.02      0.00      0.02      0.00      0.00     99.97
Average:         17      0.00      0.00      0.00      0.00      0.00    100.00
Average:         18      0.02      0.00      0.06      0.00      0.00     99.92
Average:         19      0.00      0.00      0.00      0.00      0.00    100.00
Average:         20      0.02      0.00      0.03      0.00      0.00     99.95
Average:         21      0.00      0.00      0.00      0.00      0.00    100.00
Average:         22      0.00      0.00      0.00      0.00      0.00    100.00
Average:         23      0.00      0.00      0.00      0.00      0.00    100.00

Fault present with versions:
# rpm -qa sysstat
sysstat-10.2.1-9.2.x86_64
# rpm -qa sysstat
sysstat-11.6.2-2.fc28.x86_64

Fault resolved immediately with: 
 # rpm  -qa sysstat
sysstat-11.7.2-1.x86_64

**Comment by Samodepalace** [comment]
I spoke too soon.

Even with the latest version of sysstat-11.7.2-1.x86_64, this problem is easily reproducible.
If the server is rebooted, that days saxx file will provide average figures that are null.
In the uploaded files sa04 and sa06, the server was rebooted during sa05 and it indicates

sar -P ALL -f sa05

Average:          0      0.00      0.00      0.00      0.00      0.00      0.00
Average:          1      0.00      0.00      0.00      0.00      0.00      0.00
Average:          2      0.00      0.00      0.00      0.00      0.00      0.00
Average:          3      0.00      0.00      0.00      0.00      0.00      0.00
Average:          4      0.00      0.00      0.00      0.00      0.00      0.00
Average:          5      0.00      0.00      0.00      0.00      0.00      0.00
Average:          6      0.00      0.00      0.00      0.00      0.00      0.00
Average:          7      0.00      0.00      0.00      0.00      0.00      0.00
Average:          8      0.00      0.00      0.00      0.00      0.00      0.00
Average:          9      0.00      0.00      0.00      0.00      0.00      0.00
Average:         10      0.00      0.00      0.00      0.00      0.00      0.00
Average:         11      0.00      0.00      0.00      0.00      0.00      0.00
Average:         16      0.00      0.00      0.00      0.00      0.00      0.00
Average:         17      0.00      0.00      0.00      0.00      0.00      0.00
Average:         18      0.00      0.00      0.00      0.00      0.00      0.00
Average:         19      0.00      0.00      0.00      0.00      0.00      0.00
Average:         20      0.00      0.00      0.00      0.00      0.00      0.00
Average:         21      0.00      0.00      0.00      0.00      0.00      0.00
Average:         22      0.00      0.00      0.00      0.00      0.00      0.00
Average:         23      0.00      0.00      0.00      0.00      0.00      0.00
Average:         24      0.00      0.00      0.00      0.00      0.00      0.00
Average:         25      0.00      0.00      0.00      0.00      0.00      0.00
Average:         26      0.00      0.00      0.00      0.00      0.00      0.00
Average:         27      0.00      0.00      0.00      0.00      0.00      0.00

NB: I have not attempted to compile sysstat from the source files on the SLES server from where these observations are made.
[SLES.zip](https://github.com/sysstat/sysstat/files/1785828/SLES.zip)

**Comment by sysstat** [comment]
Thank you for the attached files.
FYI sar will not display the average values for offline CPUs. That's why you don't get a line for CPUs 12, 13, 14 and 15.
Commit 9057b41 should fix the problem of values displayed as 0, except maybe for CPU "all" which is a bit more difficult to fix. Another patch will be provided soon for that.

**Comment by sysstat** [comment]
Commit ef3301e should also fix the problem now for CPU "all".
