### ISSUE TITLE
Failed to build from source on Mac OS

### ISSUE THREAD

**Issue by zhaoyi0113** [sysstat/sysstat#172]
I got error when building source code on Mac OS (version: 10.13.3 (17D47))

```
$ make
gcc -o ioconf.o -c -g -O2 -Wall -Wstrict-prototypes -pipe -O2  -DSA_DIR=\"/var/log/sa\" -DSADC_PATH=\"/usr/local/lib/sa/sadc\"  -DHAVE_SYS_PARAM_H ioconf.c
ioconf.c:523:20: error: called object type 'unsigned int' is not a function or function pointer
                        dm_major = major(aux.st_rdev);
                                   ~~~~~^
ioconf.c:524:20: error: called object type 'unsigned int' is not a function or function pointer
                        dm_minor = minor(aux.st_rdev);
                                   ~~~~~^
2 errors generated.
make: *** [ioconf.o] Error 1

```

**Comment by sysstat** [comment]
Hi,
sysstat is a Linux package, and as such, aimed at working on Linux systems. I didn't test it on other OSes.

**Comment by raswonders** [comment]
Hey,

sorry for crashing close thread but I had similar problem and I found *fix* for it. Hope you don't mind me sharing. 
I've been trying to build systat v10.1.5. Make was failing with the same complaint about unresolved major/minor macros.

I'm running gentoo with glibc
 eix glibc -c
[?] sys-libs/glibc (2.27-r6(2.2)@11/10/2018 -> ??): GNU libc C library

I've fixed it by adding following line into common.h in source dir:
#include <sys/sysmacros.h>
based on man major(3).

I can easily build latest version it seems to contain some additional check in configure.in compared to older version see below:

grep -i sysmacros configure.in
HAVE_SYS_SYSMACROS_H=
AC_CHECK_HEADERS(sys/sysmacros.h, HAVE_SYS_SYSMACROS_H=1)
if test $HAVE_SYS_SYSMACROS_H; then
   SYSMACROS="y"
   SYSMACROS="n"
AC_SUBST(SYSMACROS)

**Comment by sysstat** [comment]
Ok, so I understand that recent versions of sysstat (those including sys/sysmacros.h in common.c) compile properly on Mac.
BTW, which version of Linux are you using exactly (output of "uname -a")?

**Comment by raswonders** [comment]
I'm not on Mac but I had problem building older sysstat all the same. On my linux box (distro: gentoo rolling realease kernel 4.14 glibc 2.27-r6) it seems like problem is due to missing include for sys/sysmacros.h. Current version (understand Master on github) got it covered and includes header on condition it has been found ( during ./configure). The 10.1.5 version I've downloaded from  http://sebastien.godard.pagesperso-orange.fr/download.html and is marked as development release.

 I don't expect any fixes here just wanted to point out, what worked for me. Others having similar issues might find it useful.
