### ISSUE TITLE
[colours] high % in columns is not always bad (red)

### ISSUE THREAD

**Issue by pschiffe** [sysstat/sysstat#177]
Hi Sebastien,

in coloured sysstat's output, some high % numbers are not always bad, but they are always coloured as bad - red. Few examples are %wrqm and %rrqm in iostat, %idle in sar.. This can be pretty confusing.

Fedora bz: https://bugzilla.redhat.com/show_bug.cgi?id=1556872

peter

**Comment by sysstat** [comment]
Hi Peter,

This is in fact a misinterpretation of the color. As indicated in the manual pages:
"[...]the color (being red, yellow, or some other color) used to display a value is not indicative of any kind of issue simply because of the color. It only indicates different ranges of values."

Red is the default color used to display percentage values greater than ou equal to 75%. It doesn't mean it's bad, just that the metric is in the high range.

Sebastien

**Comment by pschiffe** [comment]
I see, sorry. But anyway in this case, red is not a very fortunate colour for such use case as it indeed represents danger or not a good state (with green on the other side) by default in general use..

**Comment by sysstat** [comment]
True, but we don't have that many different colors that can be used on both light and dark windows background!... :)
Anyway such colors can be changed. Enter, e.g. `S_COLORS_SGR="H=32;1"` to use another color (green, here) for high range values.

**Comment by stevekay** [comment]
On the subject of colors, I've got a fork of the project that permits the user to have an environment variable dictating which color to use for each percentage value.  Makes use of ANSI 256 color mode (`xterm-256color`, so works with plain old PuTTY etc).  

Example below shows how high values (`PERCENT_LIMIT_HIGH`) beyond 75 don't have to all just get a generic red. 

This of any interest?

![image](https://user-images.githubusercontent.com/4357610/47621693-63bc6800-daf3-11e8-91ce-9ede6cbb9d68.png)

**Comment by stevekay** [comment]
Fair comment, enjoyed the little experiment anyway :-)

**Comment by devZer0** [comment]
i have come here via https://bugzilla.redhat.com/show_bug.cgi?id=1556872

 "[...]the color (being red, yellow, or some other color) used to display a value is not indicative of any kind of issue simply because of the color. It only indicates different ranges of values."

i think color value read in a performance tool where there is no issue is totally misleading, especially when there is no explicit explanation of the meaning in the manpage. at least there should be a hint there about this "speciality" in philosophy.

i am a systems administrator and whatever is being marked "red" on the screen or especially in text consoles typically gets my attention and makes me raise my eyebrowe.   

you should avoid raising attention when there is no need.

**Comment by sysstat** [comment]
There **is** an explicit explanation in all the sysstat manual pages.
Moreover, as I have already said above, colors are fully customizable, so you can change that red color with any other one you prefer - And you can even remove color support totally very easily (this is indicated in the manpage too)
Remember that sar and all sysstat commands are aimed at displaying statistics just as they have been collected. Detecting or deciding that a problem exists is not sysstat's job but yours.

**Comment by d10r** [comment]
Agree that it's misleading.
I'm not a full-time sysadmin and simply don't have time to read every man page of all tools in detail.
Conventions exist in order to optimize how much we can achieve in a given timeframe.

In my case, after seeing that red number I checked the manpage for the meaning of `%wrqm`. After reading that section, I was left confused about why a high value would be flagged as red. It didn't cross my mind that the meaning of the red color in the context of a metric could have a different meaning than that value not being healthy.
Had to see that red number a few more times and get concerned enough to do an online search for it, eventually leading me to this issue.

The colors being configurable doesn't really make a difference here. Once I know that red doesn't mean what I'd expect, it can as well remain red since I now know. It's about the defaults.

All that said, thx for this tool, it's very useful!

**Comment by sysstat** [comment]
I have updated sysstat so that fewer metrics values get displayed in red when in fact they are healthy values.
See commit c2595c3 which should hopefully improve things a bit.
