### ISSUE TITLE
sar -P ALL randomly outputs incorrect all line with all values equal to zero (very old sysstat version)

### ISSUE THREAD

**Issue by lxatjouve** [sysstat/sysstat#182]
Hello,

**Warning:
Probably a non issue because**
- old OS version : Oracle Linux Server release 6.4 (seems EOL'ed to me)
- old systat version : package sysstat-9.0.4-33.el6_9.1.x86_64 (most recent available)
- high uptime :  up 372 days

Also it may be a duplicate of bug #157.

Time of occurence seems random to me.

example of "sar -P all" incorrect output :

09:50:01        CPU     %user     %nice   %system   %iowait    %steal     %idle
09:52:01        all      **0,00      0,00      0,00      0,00      0,00      0,00**
09:52:01          0      0,70      0,00      1,51      0,05      0,00     97,74
09:52:01          1      0,29      0,00      0,31      0,03      0,00     99,38
09:52:01          2      0,00      0,00      0,00      0,00      0,00      0,00

cat /proc/stat | grep cpu
cpu  508023993 13592 63937703 534877 573617 1486 17536030 0 0 0
cpu0 51324679 1859 40003556 36085 368636 1485 15780821 0 0 0
cpu1 235458213 5388 11498771 386810 10056 0 836883 0 0 0
cpu2 221241099 6344 12435375 111980 194924 0 918325 0 0 0

crontab task is :
*/2 * * * * root /usr/lib64/sa/sa1 60 1

Well... i know it's sooo old but what's your best guess?
Any reply will be much appreciated.

Best regards.

**Comment by sysstat** [comment]
Yes, it is probably a duplicate of #157.
Sometimes the number of jiffies spent by CPU "all" in various modes (user, nice, system, etc.), as given by the kernel in the /proc/stat file, decreases, which results in sar displaying values of 0.00 for this CPU.
Newer versions of sar no longer use the data provided by the kernel for CPU "all", but recalculate them using the data of each individual CPU.
You should definitely try to upgrade to check if this fixes your problem.

**Comment by edmundcraske** [comment]
Hi, don't know if this is the right place, didn't want to open a new issue if it's related, but I'm seeing issues with Ubuntu 16.04 LTS on AWS EC2 where _something_ causes an instance to stop reporting anything other than zeros for all CPU percentages when running `sar -P ALL 1 1`, but also seemingly reports zeros for other stats as well. I couldn't work out what had changed, and the instance required a reboot in order to fix it. Is this something already fixed by a newer version of sysstat than present in Ubuntu 16.04, or is it potentially a different issue?

**Comment by lxatjouve** [comment]
Thanks a lot for your very informative reply.
I'm closing the issue.
