### ISSUE TITLE
iostat: read and written values incorrect on self repeating report

### ISSUE THREAD

**Issue by c-boeckler** [sysstat/sysstat#276]
When I repeatedly start
iostat
to watch I/O progress with iostat 12.0.3 (Debian stable, sorry for the outdated version) then I see monotonic rising values for kB_read and kB_wrtn.

When I start
iostat 1
to make reports repeat themselves then the first report is accurate but the following give the values from kB_read/s and kB_wrtn/s in the columns kB_read and kB_wrtn as well. This is obviously wrong. It gets even more obvious when running iostat -h 1.

**Comment by sysstat** [comment]
This is because the first report generated by `iostat` provides statistics concerning the time since the system was booted (hence a value for `kB_read` and `kB_wrtn` rising monotonically when you enter just `iostat`). Each subsequent report covers the time since the previous report.
Please, *please*, **please** read the manual page first...!
