### ISSUE TITLE
height 4090 ?

### ISSUE THREAD

**Issue by simonmcnair** [sysstat/sysstat#384]
This implies that the svg should be taller than it is wider ?  Is this correct ?  Just curious  Should the width and height be fixed or are they arbitrary ?

Cheers

```<svg xmlns="http://www.w3.org/2000/svg" width="1060" height="4090" fill="black" stroke="#808080" stroke-width="1">```

**Comment by sysstat** [comment]
Width and height may vary depending on the options used.
Most of the time the canvas is taller than it is wide (this is because the different views are stacked vertically). But if option `packed` is used then views from the same activity are grouped on the same row (horizontally), making the canvas wider that it usually is.
Wrt height, this is a best guess and the value is often bigger that necessary (see #286).

**Comment by sysstat** [comment]
SVG canvas height will no longer be oversized in next sysstat version (12.7.6).
