### ISSUE TITLE
pidstat outputs a strange (>100%) value for %CPU

### ISSUE THREAD

**Issue by pschiffe** [sysstat/sysstat#73]
pidstat sometimes outputs a strange value (> 100%) for %CPU, %user, and %sys.

pidstat allocates a fixed size array for process information (in pid_sys_init() function). If many processes with a smaller PID are created while pidstat is running, the processes with bigger PID are not checked, meaning /proc/<PID>/stat are not checked. This can make a situation that the previous process information doesn't exist. When there is no previous process data, it's regarded as 0. When the value of the user time in /proc/<PID>/stat is 2415, pidstat outputs the following value for %user:

(2415-0)/200*100 = 1207.50 (%)

This value is over 100%, which is wrong.

One way to fix this issue is by increasing value of NR_PID_PREALLOC constant. I've found out by testing, that value of 170 fixes the issue in my environment, so I would propose value of 300 as a safe number. Other solutions are also possible, such as using dynamic array..

What do you think?

**Comment by pschiffe** [comment]
here is a script which can be used to reproduce this issue:
https://gist.github.com/pschiffe/1c53d178caf6bd512098

usage:
just run the script and then:
$ grep hostsdata /tmp/pidstat.log

You can find there the problematic values in 3., 4. and 5. columns.

**Comment by sysstat** [comment]
Thank you Peter for your investigation on this problem.
The solution should probably be a mix of the two. For example, NR_PID_PREALLOC could be increased to 100 or 150 (instead of its current value of 10), and PID array should be reallocated whenever we need more space (when this case happens, I can imagine reallocating the array to its current value + 2 * NR_PID_PREALLOC to avoid having to count the total number of PID in the system again).
If you have any comments, please tell me. I will try to implement this kind of solution later when I have more time (unless of course you feel ready to send me the corresponding patch :wink: )

**Comment by pschiffe** [comment]
Sorry for delay, I've prepared a patch, what do you think?

**Comment by sysstat** [comment]
I think that it's always a pleasure to get a patch from you :smile: 
Just one thing you missed here: You also need to update the read_task_stats() function which is called from read_stats(). It needs exactly the same changes than those made for read_stats().
Please can you update your patch and resend?
Thanks.

**Comment by pschiffe** [comment]
Thanks for the review. Fixed.

**Comment by pschiffe** [comment]
@sysstat ,

when testing this issue and patch in our distro using attached reproducer, we sometimes see value `101` in the `%CPU` column. For example:
```
1456846297  1000       470   76.00   25.00    0.00  101.00     3      24.00      0.00  114852    2924   0.02      0.00      0.00      0.00       0  sh -c while :; do read hostsdata < /etc/hosts; done
```

I captured values of the following variables when this happens:
```
pstp->utime = 291
pstp->stime = 100
pstc->utime = 367
pstc->stime = 125
```

After applying `SP_VALUE` macro on them, you just get `101`. Are these `stime` and `utime` values being modified in the sysstat? I didn't find anything, so I'm thinking that the statistics provided by the kernel might be inaccurate.

How would you propose to solve this? Add the check if the value is > 100 output 100?

Thanks,

peter

**Comment by sysstat** [comment]
Peter,
No, `stime` and `utime` are not modified. So maybe the statistics provided by the kernel are actually inaccurate. Or maybe this is because of the way sysstat works (things are not done atomically: pidstat reads system uptime to determine the time interval _then_ the tasks counters)...
Wrt the fix, I think that adding a check to output 100 if the value is > 100 is the right thing to do.

Regards.
Sebastien.

**Comment by pschiffe** [comment]
Thanks for the advice. What do you think about patch like this? Would it be enough?
```
diff --git a/common.h b/common.h
index 4ad5023..992ea33 100644
--- a/common.h
+++ b/common.h
@@ -126,7 +126,7 @@
  * HZ is 1024 on IA64 and % should be normalized to 100.
  */
 #define S_VALUE(m,n,p) (((double) ((n) - (m))) / (p) * HZ)
-#define SP_VALUE(m,n,p)        (((double) ((n) - (m))) / (p) * 100)
+#define SP_VALUE(m,n,p)        ((((double) ((n) - (m))) / (p)) > 1.0 ? 100 : (((double) ((n) - (m))) / (p) * 100))
 
 /*
  * Under very special circumstances, STDOUT may become unavailable.

```

**Comment by stevekay** [comment]
Instead of

    ((((double) ((n) - (m))) / (p)) > 1.0 ? 100 : (((double) ((n) - (m))) / (p) * 100))

How about using the MINIMUM macro that's declared a few lines later ?  Shorter and avoids repetition of the expression.

    MINIMUM((((double) ((n) - (m))) / (p) * 100),100)

**Comment by sysstat** [comment]
@pschiffe Yes, I think that such a patch would be enough, but with the following comments:
1) Replace "100" with "100.0" just to make sure that we return a floating point number and not an integer,
2) Beware of percentage values which can *really* be greater than 100%: `%commit` displayed by `sar -r` is such a value (I don't think that there are other cases among the metrics displayed by sysstat commands.)

@stevekay You're right. We also could use the MINIMUM macro because it's a (very little) bit shorter. Yet I prefer the solution suggested by @pschiffe because it's a (very little) bit more efficient (with one division by 100 dropped). OK, I must admit this is debatable... :-)

**Comment by pschiffe** [comment]
Thanks for your comments. I like the @stevekay solution because it's more readable, and the performance penalty is not that bad I guess.

Nevertheless, mentioning your second note in the comment, I think I need to create a new macro, which will be limiting the value to 100, and use that where appropriate. I will prepare the PR.

**Comment by portante** [comment]
@sysstat, do you think the optimizer won't end up with the same code?

**Comment by sysstat** [comment]
Don't worry guys, I won't veto any solution since they are globally equivalent... :-)
@pschiffe Thank you for the PR. Merge will happen soon.

**Comment by delta160** [comment]
What about a multi threaded process, I have traced Java GC with pidstat and historically seen CPU value of e.g. 1200%, for one process, typically just a short lived spike, however nowadays CPU in pidstat seems limited to 100%, and I am quite sure that I still have Java GC spikes :-), I think the change occurred when I moved from RHEL 6 to RHEL 7, 
If I add the -t flag I can see total CPU usage for the process summing up way over 100%; I would contend that without the -t flag the CPU value ought to be the amount of CPU consumed by all threads of the process. ( unless -I is used when it should be divided by number of cores)

**Comment by sysstat** [comment]
@delta160 Please would it be possible to send me (sysstat at orange dot fr) a small script/program to reproduce the problem, i.e. a program that creates a multithreaded task whose total CPU usage is more than 100% (I guess I could have written it but I really don't have much time for now).
Thanks.

**Comment by vchigrin** [comment]
Here is example program, compile with ```gcc -pthread test.c```
```
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

void* foo(void* unused) {
  while (1);
  return NULL;
}

int main(int argc, const char* argv[]) {
  int i = 0;
  int thread_count = 0;
  if (argc != 2) {
    printf("Usage: %s thread_count\n", argv[0]);
    return 1;
  }
  thread_count = atoi(argv[1]);
  printf("Using %d threads\n", thread_count);
  for (i = 0; i < thread_count - 1; ++i) {
    pthread_t thread;
    if (pthread_create(&thread, NULL, &foo, NULL) != 0) {
      printf("Failed create thread\n");
      return 1;
    }
  }
  while(1);
  return 0;
}
```

Try run it with different number of threads like ```./a.out 1```, ```./a.out 2``` ```./a.out 3``` etc. See output of other performance monitoring tools like top, ps - they shows CPU utilization 100%, 200%, 300% accordingly. ```pidstat 1``` on the other hand always shows 100%, doesn't telling us how much resources task actually consume. 

I think current pidstat behavior is completely wrong, making it unusable for monitoring processes, that attempt take advantage of modern multi-core CPUs, by launching multiple threads. I think changes from 52977c479d3de1cb2535f896273d518326c26722 should be reverted.

**Comment by sysstat** [comment]
At last I could take some time to tackle this issue.
Commit a63e879 reverts changes from 52977c4 and should hopefully fix the problem. The tests I made show values consistent with those of other programs (top...)
There will still be some corner cases where CPU value will be slightly greater than 100% because of inaccurate statistics read from the kernel (this was the problem that the initial commit 52977c4 was intended to fix) but this is definitely less problematic anyway.
@delta160 @vchigrin Thanks for your help (and patience :-) )

**Comment by vchigrin** [comment]
@sysstat  Thank you for maintaining so nice set of tools! :)

**Comment by tongxiaoge1001** [comment]
So, is that a question? If it is, should sysstat or kernel fix it? 
“There will still be some corner cases where CPU value will be slightly greater than 100% because of inaccurate statistics read from the kernel.”  .Should we feed back the problem to the kernel to fix it?

**Comment by sysstat** [comment]
@tongxiaoge1001 Yes this may actually be annoying to get some values greater than 100% when they should not. But I can't imagine ask the kernel maintainers to fix the thing. Kernel statistics will always be (slightly) inaccurate because code will always be constrained  by performance considerations (at least I think so). So if we really need a fix then sysstat should provide it. Any suggestions how to do that?

**Comment by zchazc** [comment]
About "Kernel statistics will always be (slightly) inaccurate..." ,the Linux Kernel Documentation provides explanations about why:

- From [cpu-load](https://www.kernel.org/doc/html/latest/admin-guide/cpu-load.html)
>In most cases the `/proc/stat` information reflects the reality quite closely, however due to the nature of how/when the kernel collects this data sometimes it can not be trusted at all.
- From [iostat](https://www.kernel.org/doc/html/latest/admin-guide/iostats.html)
>To avoid introducing performance bottlenecks, no locks are held while modifying these counters. This implies that minor inaccuracies may be introduced when changes collide, so (for instance) adding up all the read I/Os issued per partition should equal those made to the disks ... but due to the lack of locking it may only be very close.

It appears that between accuracy and performance, the kernel developers chose to prioritize performance.
