### ISSUE TITLE
read numbers on possibly wrong positions for Icmp statistics from /proc/net/snmp on Ubuntu 14.04

### ISSUE THREAD

**Issue by jzy1688** [sysstat/sysstat#77]
In re_stats.c, &st_net_icmp->InEchos is read from the eighth position(start from 1) of the line while, in Ubuntu 14.04 proc/net/snmp, InEchos for Icmp is on the ninth position. Hence,a ll the following metrics for Icmp may be wrong as well.

**Comment by beejeebus** [comment]
yep, this seems to be true on at least Trusty, Precise and Centos7.

**Comment by portante** [comment]
Also appears to be true on RHEL 7.

This change looks good to me.

**Comment by sysstat** [comment]
@portante: You're right. This bug is due to the addition of the field "InCsumErrors" after "InErrors" in the ICMP line. We can also note that this field "InCsumErrors" was added to the TCP and UDP
lines too, but smartly enough to be after the pre existing fields :grinning: .

@beejeebus: Your change is OK for the new pattern. But maybe we should look for the existence of the field "InCsumErrors" to know which pattern we have to deal with and decide if we have to skip this additional field or not.
