### ISSUE TITLE
combination of -P with other options doesn't work

### ISSUE THREAD

**Issue by arcolife** [sysstat/sysstat#86]
Hi,

FYI, while I was trying out different combinations, I came across this particular situation (bug?) where, when I supply options as follows:
```
1. LC_ALL=C sadf -d  -- -r -v | less
2. LC_ALL=C sadf -d  -- -r -P 0 | less
3. -bBdFHqrRSuvwWy -I SUM -I XALL -m ALL -n ALL -u ALL -P ALL
```

The option 1 gives me memory and kernel tables/inode stats together. Thats fine.
But option 2 doesn't give me [memory + cpu#0] stats together.
While 3'rd option, the equivalent of '-A', works well with -P ALL.

Any idea, as to why?

Thanks already,
Archit

**Comment by sysstat** [comment]
Hi,

No bugs here... Here is how things work:
Option -P indicates for which processors **CPU-related statistics** are to be reported (eg. CPU utilization [-u], clock frequency [-m CPU], etc. ).
Another thing to know is that if you don't specify any activity then sar will use CPU activity as the default (equivalent to option -u).

With your 2nd example, you tell sar that statistics have to be displayed for CPU#0. You also tell it to display memory statistics only. This kind of activity (memory stats) is not affected by option -P since it is not related to CPU. And since you specified an activity, sar won't use the default one (option -u for CPU utilization). As a consequence only memory stats are displayed.

**Comment by sysstat** [comment]
Oh, I explained things using the sar command... But things are quite the same with sadf. :wink:

**Comment by arcolife** [comment]
@sysstat Thanks for the explanation ! :)

**Comment by arcolife** [comment]
@sysstat out of curiosity, any idea how could I detect (using -- with sadf) as to which option is not working (resulting in failure of the command, and the 'help' dialogue eventually).. if, for example: I supply `-bBFwW` ..but somehow `-F` is failing; but now since the automation script I'm running shouldn't really fail (we need all we can get from the options).. Worst case would be to test each option individually?

**Comment by arcolife** [comment]
oh I see. So I was using this rhel65 script of sadf to run on an older version of sa binary. Whereas the newer versions (like for f19) is much more robust. In that case, I think we can't do anything about that right? Or I should probably patch that script with the changes included in newer sadf versions which fails silently if combined with other options or says "requested activities not available"..
