### ISSUE TITLE
Build failure under CentOS 6 using 11.3.1

### ISSUE THREAD

**Issue by maoueh** [sysstat/sysstat#97]
Hi,

I tried building `sysstat` under CentOS 6 using the default instructions:

```
./configure
make
make install
```

However, I get a lot of `make: o: Command not found` when trying to compile the translation files like:

```
o nls/af.gmo nls/af.po
make: o: Command not found
```

Not sure if `o` is a real command that is missing or if there is something fishy in the build directly. Current simple workaround is to disable translation support when building using:

```
./configure --disable-nls
make
make install
```

I can provide you the full configure and build log files if needed.

Regards,
Matt

**Comment by pschiffe** [comment]
You are probably missing a `gettext` package.

**Comment by maoueh** [comment]
I will test this, thanks. Shouldn't `configure` bails if translation is enabled and `gettext` (or the actual dependency is not present)?

**Comment by maoueh** [comment]
Confirmed, installing `gettext` fixed the compilation problem. I'm not very familiar with `gettext`, it this is also required at runtime afterward? My guess would be that it is needed only at compilation time, but I would rather be sure of the answer as I'm packaging `sysstat` latest version as a `rpm`, so I would add a dependency on it if required and not otherwise.

Feel free to close if you feel there is no need to fix anything here. On my side, I would side an error from `configure` or a note in the compilation process somewhere (probably `INSTALL` or on the website).

Regards,
Matt

**Comment by pschiffe** [comment]
`gettext` is required only at build time. I think the proper fix here should be that `configure` detects the `gettext` and fails if it's missing and translations are enabled. @sysstat will you check it? I might send a PR if I have some time, but can't promise.

**Comment by sysstat** [comment]
@pschiffe I can check it but only in a few weeks as I'm currently travelling.
In the meantime PR are welcome of course :-)

**Comment by stevekay** [comment]
https://github.com/sysstat/sysstat/pull/98

**Comment by sysstat** [comment]
@maoueh @pschiffe NLS is enabled by default with sysstat, but if `configure` doesn't find the required include files (`libintl.h` and `locale.h`) then NLS is _disabled_. OTOH if the `gettext`package required at build time is not found, `configure` already warns the user (eg. `WARNING: xgettext command not found!`). I think that the proper fix should then to *disable* NLS instead of only warning the user, but not to fail and stop.
@stevekay Please update your PR accordingly: `configure` should display something like `WARNING: xxxxx command not found: Disabling NLS` then set the NLS variable to *n* (no). And BTW, don't change the `configure` file. Update the `configure.in` file instead (see at lines 277+), the `configure`script will be automatically created by `autoconf`. Thank you for your help.

**Comment by stevekay** [comment]
Thanks for the advice and patience.  Revised PR created.

**Comment by sysstat** [comment]
@stevekay OK, I'm a bit fussy (sorry), but in fact here is how I would write the patch:

1) Keep the tests for each command (xgettext, msgfmt, msgmerge) as I originally wrote them. But if one of the commands doesn't exist, also set a variable XXX (initially set to false for example) to true in addition to displaying the warning message.
2) Then add a new test: If the NLS variable is set to *y* and the XXX variable is set to true then display `Disabling NLS` and set the NLS variable to *n*. In this way NLS will be disabled if **any** of the 3 commands doesn't exist (and not only if the xgettext command doesn't exist).

Last, don't forget to send me your PR. I will test/merge it when I'm back home.
Thanks again.

**Comment by stevekay** [comment]
Good points.  Revised PR created.
https://github.com/sysstat/sysstat/pull/100
